Add Host logging to LittleProxy
verygoodsecurity/LittleProxy pull request #11
Opened 2017-05-08 14:22 UTC by igor-dmitriev

2017-05-08 14:27 UTC, igor-dmitriev commented on src/main/java/org/littleshoot/proxy/impl/ProxyConnection.java
> +    }
we can't retrieve remoteUser from netty HttpRequest, it means it's impossible to get authenticated user for Forward Proxy

2017-05-08 14:49 UTC, zdmytriv requested changes

2017-05-08 14:49 UTC, zdmytriv commented on src/main/java/org/littleshoot/proxy/impl/ProxyConnection.java
> +     *
Keep old formatting

2017-05-08 14:49 UTC, zdmytriv commented on src/main/java/org/littleshoot/proxy/impl/ProxyConnection.java
> +     *
Keep old formatting everywhere

2017-05-08 14:49 UTC, zdmytriv commented on src/main/java/org/littleshoot/proxy/impl/ProxyConnection.java
> +            } catch (RuntimeException ex) {
what would happen if it fail with plain `Exception`? We wouldn't log it?

2017-05-08 14:49 UTC, zdmytriv commented on src/main/java/org/littleshoot/proxy/impl/ProxyConnection.java
> +import io.netty.channel.Channel;
Keep old `imports`

2017-05-08 14:49 UTC, zdmytriv commented on src/main/java/org/littleshoot/proxy/impl/ProxyConnection.java
> +import static org.littleshoot.proxy.impl.ConnectionState.AWAITING_CHUNK;
Keep old static imports

2017-05-08 14:49 UTC, zdmytriv commented on src/main/java/org/littleshoot/proxy/HttpProxyException.java
> +public class HttpProxyException extends RuntimeException {
I think `ProxyRuntimeException` would sound better

2017-05-08 14:49 UTC, zdmytriv commented on src/main/java/org/littleshoot/proxy/HttpProxyException.java
> +    super(e.getMessage() + ", details: " + details, e);
`String.format()` ?

2017-05-08 15:05 UTC, zdmytriv commented on src/main/java/org/littleshoot/proxy/impl/ProxyConnection.java
> +            } catch (RuntimeException ex) {
OK, I see that it wouldn't throw Exception because there is no throws in method signature

2017-05-11 15:49 UTC, igor-dmitriev commented
discussed with @zdmytriv and got an idea to close the PR, we don't need it, it's not really useful, we can't do it effectively.

2017-05-16 14:15 UTC, osklyarenko commented
thanks @igor-dmitriev. so i'm closing this pull then.

2017-05-16 14:15 UTC, closed without merging